default: &default
  authorize_params:
    scope: /authenticate
  client_options:
    site: https://pub.orcid.org/v2.1
    authorize_url: http://orcid.org/oauth/authorize?show_login=true
    token_url: https://pub.orcid.org/oauth/token

sandbox: &sandbox
  authorize_params:
    scope: /authenticate
  client_options:
    site: https://sandbox.orcid.org/v2.1
    authorize_url: http://sandbox.orcid.org/oauth/authorize?show_login=true
    token_url: https://sandbox.orcid.org/oauth/token

development:
  <<: *default

test:
#  <<: *sandbox
  <<: *default

production:
  <<: *default
